### ISSUE TITLE
Not validating

### ISSUE THREAD

**Issue by C3Projects** [bhaumikpatel/reCAPTCHA.MVC.Demo#2]
As at the time of writing, all validations fail on the the demo site after you submit.

**Comment by bhaumikpatel** [comment]
When I am checked reCAPTCHA analytics in admin panel I got spam index might me reason for demo site not working. When I am check-in local project it should be woking properly. 

I am suggesting Delete key and re-create reCAPTCHA key then should be work.

**Now Demo Working Fine**

![recaptcha analytics](https://cloud.githubusercontent.com/assets/1846228/9697685/0709f67c-53b5-11e5-9b62-f820aa1f758d.png)
